//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hspi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hspi.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;accordionstatus{0}&quot; class=&quot;accordion md-accordion&quot; aria-multiselectable=&quot;true&quot;&gt;
        ///	&lt;div class=&quot;card&quot;&gt;
        ///	  &lt;div class=&quot;card-header&quot; id=&quot;headingstatus{0}&quot;&gt;
        ///		  &lt;a data-toggle=&quot;collapse&quot; data-parent=&quot;#accordionstatus{0}&quot; href=&quot;#collapsestatus{0}&quot; aria-expanded=&quot;false&quot; aria-controls=&quot;collapsestatus{0}&quot;&gt;
        ///				&lt;h5 class=&quot;mb-0&quot;&gt;{1}&lt;i class=&quot;fas fa-angle-down rotate-icon&quot;&gt;&lt;/i&gt;&lt;/h5&gt;
        ///		  &lt;/a&gt;
        ///	  &lt;/div&gt;
        ///	  &lt;div id=&quot;collapsestatus{0}&quot; class=&quot;collapse&quot; aria-labelledby=&quot;headingstatus{0}&quot; data-parent=&quot;#accordi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CollapseHeader {
            get {
                return ResourceManager.GetString("CollapseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ///function refreshZWaveParameter(homeId, nodeId, parameter, idMessage, idValueWrapper, idValue) {
        ///	var formObject = {
        ///		   homeId: homeId,
        ///		   nodeId: nodeId,
        ///		   parameter: parameter,
        ///		   operation: &quot;GET&quot;
        ///	   };
        ///	   
        ///	$(&apos;#&apos; + idValueWrapper).attr(&quot;hidden&quot;,true);
        ///	$(&apos;#&apos; + idMessage).html(&apos;&apos;)
        ///	$(&apos;#&apos; + idMessage).addClass(&quot;spinner-border&quot;);
        ///	$(&apos;#&apos; + idMessage).show();	
        ///	
        ///	$.ajax({
        ///		type: &quot;POST&quot;,
        ///		async: &quot;true&quot;,
        ///		url: &apos;/ZWaveInformation/Update&apos;,
        ///		cache:false,
        ///		data: JSON.strin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostForRefreshScript {
            get {
                return ResourceManager.GetString("PostForRefreshScript", resourceCulture);
            }
        }
    }
}
