//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSPI_ZWaveParametersTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSPI_ZWaveParametersTest.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;approval_requested&quot;:0,&quot;approved&quot;:1,&quot;beaming&quot;:&quot;1&quot;,&quot;database_id&quot;:75,&quot;db_version&quot;:6,&quot;deleted&quot;:0,&quot;description&quot;:&quot;Smart Energy Switch&quot;,&quot;device_ref&quot;:&quot;0003:0006&quot;,&quot;exclusion&quot;:&quot;&lt;ol&gt;&lt;li&gt;Put the controller in exclusion mode&lt;\/li&gt; &lt;li&gt;Press the button located between the LED&lt;\/li&gt; &lt;\/ol&gt;&lt;p&gt;If the Aeon Labs Smart Energy Switch was removed from the Z-Wave network, the LED will be blinking. If the Aeon Labs Smart Energy Switch was not successfully removed from the Z-Wave network, the LED will either be on or off (dependi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AeonLabsOpenZWaveDBDeviceJson {
            get {
                return ResourceManager.GetString("AeonLabsOpenZWaveDBDeviceJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;search_filter&quot;:{&quot;manufacturer&quot;:134,&quot;filter&quot;:&quot;0003:0006&quot;},&quot;total&quot;:1,&quot;devices&quot;:[{&quot;label&quot;:&quot;DSC06&quot;,&quot;description&quot;:&quot;Smart Energy Switch&quot;,&quot;manufacturer_name&quot;:&quot;AEON Labs&quot;,&quot;id&quot;:75,&quot;version_min&quot;:&quot;0.000&quot;,&quot;version_max&quot;:&quot;255.255&quot;,&quot;protocol_version&quot;:&quot;2.078&quot;,&quot;manufacturer_ref&quot;:134,&quot;uuid&quot;:&quot;dsc06&quot;,&quot;category&quot;:&quot;Battery&quot;}]}.
        /// </summary>
        internal static string AeonLabsOpenZWaveDBDeviceListJson {
            get {
                return ResourceManager.GetString("AeonLabsOpenZWaveDBDeviceListJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;approval_requested&quot;: 0,
        ///  &quot;approved&quot;: 1,
        ///  &quot;beaming&quot;: &quot;1&quot;,
        ///  &quot;database_id&quot;: 1113,
        ///  &quot;db_version&quot;: 12,
        ///  &quot;deleted&quot;: 0,
        ///  &quot;description&quot;: &quot;description&quot;,
        ///  &quot;device_ref&quot;: &quot;0002:0001&quot;,
        ///  &quot;exclusion&quot;: &quot;exclusion&quot;,
        ///  &quot;first_approval_time&quot;: &quot;0000-00-00 00:00:00&quot;,
        ///  &quot;frequently_listening&quot;: &quot;0&quot;,
        ///  &quot;inclusion&quot;: &quot;inclusion&quot;,
        ///  &quot;label&quot;: &quot;LZW30-SN&quot;,
        ///  &quot;last_approval_time&quot;: &quot;2021-09-23 23:44:54&quot;,
        ///  &quot;listening&quot;: &quot;1&quot;,
        ///  &quot;overview&quot;: &quot;overview&quot;,
        ///  &quot;protocol_version&quot;: &quot;6.004&quot;,
        ///  &quot;routing&quot;: &quot;1&quot;,
        ///  &quot;usage&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicTopLevelOpenZwaveDBJson {
            get {
                return ResourceManager.GetString("BasicTopLevelOpenZwaveDBJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;search_filter&quot;:{&quot;manufacturer&quot;:12,&quot;filter&quot;:&quot;4447:3036&quot;},&quot;total&quot;:2,&quot;devices&quot;:[{&quot;label&quot;:&quot;HS-WD200+&quot;,&quot;description&quot;:&quot;Scene Capable Wall Dimmer Switch&quot;,&quot;manufacturer_name&quot;:&quot;HomeSeer Technologies&quot;,&quot;id&quot;:806,&quot;version_min&quot;:&quot;0.000&quot;,&quot;version_max&quot;:&quot;5.009&quot;,&quot;protocol_version&quot;:&quot;4.061&quot;,&quot;manufacturer_ref&quot;:12,&quot;uuid&quot;:&quot;hswd200&quot;,&quot;category&quot;:&quot;Battery&quot;},{&quot;label&quot;:&quot;HS-WD200+&quot;,&quot;description&quot;:&quot;Scene Capable Wall Dimmer Switch&quot;,&quot;manufacturer_name&quot;:&quot;HomeSeer Technologies&quot;,&quot;id&quot;:1040,&quot;version_min&quot;:&quot;5.011&quot;,&quot;version_max&quot;:&quot;255.255&quot;,&quot;protoco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeseerDimmerOpenZWaveDBDeviceListJson {
            get {
                return ResourceManager.GetString("HomeseerDimmerOpenZWaveDBDeviceListJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;approval_requested&quot;: 0,
        ///  &quot;approved&quot;: 1,
        ///  &quot;beaming&quot;: &quot;1&quot;,
        ///  &quot;database_id&quot;: 1040,
        ///  &quot;db_version&quot;: 8,
        ///  &quot;deleted&quot;: 0,
        ///  &quot;description&quot;: &quot;Scene Capable Wall Dimmer Switch&quot;,
        ///  &quot;device_ref&quot;: &quot;4447:3036&quot;,
        ///  &quot;exclusion&quot;: &quot;&lt;p&gt;Put your Z-Wave controller into exclusion mode, tap the paddle of your new HomeSeer dimmer to begin the inclusion process. This will take a few moments to complete.&lt;/p&gt;&quot;,
        ///  &quot;first_approval_time&quot;: &quot;0000-00-00 00:00:00&quot;,
        ///  &quot;frequently_listening&quot;: &quot;0&quot;,
        ///  &quot;inclusion&quot;: &quot;&lt;p&gt;Put your Z-Wave cont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeseerDimmerOpenZWaveDBFullJson {
            get {
                return ResourceManager.GetString("HomeseerDimmerOpenZWaveDBFullJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;approval_requested&quot;:0,&quot;approved&quot;:1,&quot;beaming&quot;:&quot;1&quot;,&quot;database_id&quot;:806,&quot;db_version&quot;:12,&quot;deleted&quot;:0,&quot;description&quot;:&quot;Scene Capable Wall Dimmer Switch&quot;,&quot;device_ref&quot;:&quot;4447:3036&quot;,&quot;exclusion&quot;:&quot;&lt;p&gt;Put your Z-Wave controller into exclusion mode, tap the paddle of your new HomeSeer dimmer to begin the inclusion process. This will take a few moments to complete.&lt;\/p&gt;&quot;,&quot;first_approval_time&quot;:&quot;2018-03-21 20:58:27&quot;,&quot;frequently_listening&quot;:&quot;0&quot;,&quot;inclusion&quot;:&quot;&lt;p&gt;Put your Z-Wave controller into inclusion mode, tap the paddle of y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeseerDimmerOpenZWaveDBFullOlderJson {
            get {
                return ResourceManager.GetString("HomeseerDimmerOpenZWaveDBFullOlderJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// 
        ///  &quot;database_id&quot;: 5623, 
        ///  &quot;parameters&quot;: [
        ///        {
        ///      &quot;param_id&quot;: 3,     
        ///      &quot;size&quot;: 2,
        ///      &quot;bitmask&quot;: 0,
        ///      &quot;default&quot;: 0,
        ///      &quot;minimum&quot;: 0,
        ///      &quot;maximum&quot;: 32767,
        ///      &quot;read_only&quot;: &quot;1&quot;,
        ///      &quot;write_only&quot;: &quot;0&quot;,
        ///      &quot;limit_options&quot;: &quot;1&quot;,
        ///      &quot;id&quot;: 7247,
        ///      &quot;options&quot;: []
        ///    }]
        ///}.
        /// </summary>
        internal static string ParameterReadOnlyOpenZWaveDBJson {
            get {
                return ResourceManager.GetString("ParameterReadOnlyOpenZWaveDBJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// 
        ///  &quot;database_id&quot;: 5623, 
        ///  &quot;parameters&quot;: [
        ///        {
        ///      &quot;param_id&quot;: 3,
        ///      &quot;label&quot;: &quot;Auto Off Timer&quot;,
        ///      &quot;description&quot;: &quot;Auto Off Timer&quot;,
        ///      &quot;units&quot;: &quot;seconds&quot;,
        ///      &quot;overview&quot;: &quot;&lt;p&gt;Automatically turns the switch off after x amount of seconds&lt;/p&gt; &lt;p&gt;0 = Disabled&lt;/p&gt; &lt;p&gt;1= 1 second&lt;/p&gt; &lt;p&gt;32767 = 32767 seconds&lt;/p&gt;&quot;,
        ///      &quot;size&quot;: 2,
        ///      &quot;bitmask&quot;: 0,
        ///      &quot;default&quot;: 0,
        ///      &quot;minimum&quot;: 0,
        ///      &quot;maximum&quot;: 32767,
        ///      &quot;read_only&quot;: &quot;0&quot;,
        ///      &quot;write_only&quot;: &quot;0&quot;,
        ///      &quot;reincl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParameterWithNoOptionOpenZWaveDBJson {
            get {
                return ResourceManager.GetString("ParameterWithNoOptionOpenZWaveDBJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// 
        ///  &quot;database_id&quot;: 563, 
        ///  &quot;parameters&quot;: [
        ///    {
        ///      &quot;param_id&quot;: 1,
        ///      &quot;label&quot;: &quot;Power On State&quot;,
        ///      &quot;description&quot;: &quot;Power On State&quot;,
        ///      &quot;units&quot;: &quot;&quot;,
        ///      &quot;overview&quot;: &quot;&lt;p&gt;When power is restored, the switch reverts to either On, Off or last level&lt;/p&gt; &lt;p&gt;0 = Returns to State before Power Outage&lt;/p&gt; &lt;p&gt;1 = On&lt;/p&gt; &lt;p&gt;2 = Off&lt;/p&gt;&quot;,
        ///      &quot;size&quot;: 1,
        ///      &quot;bitmask&quot;: 0,
        ///      &quot;default&quot;: 0,
        ///      &quot;minimum&quot;: 0,
        ///      &quot;maximum&quot;: 2,
        ///      &quot;read_only&quot;: &quot;0&quot;,
        ///      &quot;write_only&quot;: &quot;0&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParameterWithOptionOpenZWaveDBJson {
            get {
                return ResourceManager.GetString("ParameterWithOptionOpenZWaveDBJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// 
        ///  &quot;database_id&quot;: 5623, 
        ///  &quot;parameters&quot;: [
        ///        {
        ///      &quot;param_id&quot;: 3,     
        ///      &quot;size&quot;: 2,
        ///      &quot;bitmask&quot;: 0,
        ///      &quot;default&quot;: 0,
        ///      &quot;minimum&quot;: 0,
        ///      &quot;maximum&quot;: 32767,
        ///      &quot;read_only&quot;: &quot;0&quot;,
        ///      &quot;write_only&quot;: &quot;1&quot;,
        ///      &quot;limit_options&quot;: &quot;1&quot;,
        ///      &quot;id&quot;: 7247,
        ///      &quot;options&quot;: []
        ///    }]
        ///}.
        /// </summary>
        internal static string ParameterWriteOnlyOpenZWaveDBJson {
            get {
                return ResourceManager.GetString("ParameterWriteOnlyOpenZWaveDBJson", resourceCulture);
            }
        }
    }
}
